import type { Metadata } from "next";
import "./globals.css";
import { Mulish } from 'next/font/google';

const mulish = Mulish({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "MonopolyBank",
  description: "Generated by Carlos Santos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.className} antialiased bg-zinc-800`}
      >
        {children}
      </body>
    </html>
  );
}
